# Generated by Django 2.1.4 on 2018-12-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181225_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmstring',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfirmString',
        ),
    ]
